---

version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
    - ELASTIC_PASSWORD=wibble
    ports:
      - "9200:9200"
    networks:
    - esnet

  elasticsearch_slaves:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    deploy:
      replicas: 3
    environment:
    - "discovery.zen.ping.unicast.hosts=elasticsearch"
    - ELASTIC_PASSWORD=wibble
    ports:
      - "9201:9200"
    networks:
    - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    environment:
    - "elasticsearch.password=wibble"
    ports:
      - "5601:5601"
    networks:
    - esnet

networks:
  esnet:


